live_config_reload = true

[shell]
program = "/opt/homebrew/bin/fish"

[window]
dimensions =  { columns = 100, lines = 30 }
padding = { x = 10, y = 30 }
dynamic_padding = true
decorations = "Transparent"

[mouse]
hide_when_typing = true
